apiVersion: apps/v1
kind: Deployment
metadata:
  name: helloworld-deploy
spec:
  selector:
    matchLabels:
      app: helloworld
  replicas: 1
  template:
    metadata:
      labels:
        app: helloworld
    spec:
      containers:
      - name: helloworld
    # enter the path to your image, be sure to include the correct region prefix
        image: ${REGION}.ocir.io/${TENANCY_NAME}/${REPO_NAME}:${GIT_COMMIT}
        ports:
        - containerPort: 5000
      imagePullSecrets:
    # enter the name of the secret you created
      - name: ocirsecret
---
apiVersion: v1
kind: Service
metadata:
  name: helloworld-service
spec:
  type: LoadBalancer
  ports:
  - port: 5000
    protocol: TCP
    targetPort: 5000
  selector:
    app: helloworld
